---
title: "Troubleshooting"
author: "Abigail Stamm, with some warnings modified from Tom Talbot & Gwen Babcock"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Troubleshooting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Installation

These errors and warnings are related to installation of the Geomasker. 

## There is an issue with the package installation

Usually, the issue is that vignettes fail to install. To fix this, try one of these solutions.

1. If installing from the zipped file, uninstall the package, restart R, and reinstall the package.
2. If installing from GitHub, run this code: 

> devtools::install_github("ajstamm/geomask", dependencies = TRUE, 
>                          build_vignettes = TRUE)


# User input

These errors and warnings are related to the user input portion of the Geomasker.

## I'm not seeing the dialog boxes

The dialog boxes may be hidden beneath other windows. Close or minimize extraneous windows or check the task bar for an icon that looks like a thin quill/feather.

<!-- # Running the Geomasker -->

<!-- These errors and warnings may occur while the Geomasker is processing your shapefile. -->

# Output files

These errors and warnings are related to files produced by the Geomasker.

## Variable names in my final shapefile are truncated

This appears to be an issue with the DBF driver used by the foreign package. The driver identifies at least one variable name that it interprets as too long (over 10 characters), but truncates several variable names, not just the offender. The data otherwise still write correctly. This should be addressed as of v1.4.0.

## When I import my shapefile into my GIS program, a blank map appears

When importing a shapefile, be sure that the same projection is selected in the GIS program as in the original shapefile. The shapefile's projection information is included in the log file generated by the Geomasker.

## No KML file is produced

Make sure to select that you want a KML file. Check the log file generated by the Geomasker to confirm that you requested one. Wait for the “Tool is finished” message to display before closing the windows/pop-ups generated by the Geomasker.

## Data do not appear in Google Earth

When I click on a region in Google Earth, the data do not appear in the description call-out. The data may not appear in Google Earth 4.x, so use Google Earth 5.0 or greater. Try clicking on the area's link in the left sidebar to see the data.

## Warning for large numbers not writing correctly

A message like this appears in the R console: 

>	In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  ... :
> GDAL Message 1: Value 199678888 of field ALAND of feature 40 not successfully written. 

This warning occurs when there are numeric fields with very large values, such as square meters of land or water areas. In testing, the output values matched the input values. You can verify this yourself by checking the original DBF file against the masked file. To avoid this warning, set large number fields to character or remove them from your DBF before running the Geomasker.

