#' Confirm geomasking settings
#'
#' @description
#' This function opens a dialog window for the user to select whether the
#' selected settings for GAT are correct.
#'
#' @details
#' This function reads in the lists created during the user input portion of
#' the GAT tool. As such, it requires that the inputted lists contain the same
#' elements as those generated by the Geomasker.
#'
#' @param maskvars   List of objects needed to calculate masked points. It
#'                   contains the numbers min and max, the boolean projection,
#'                   and the strings unit, point_id, and bound_id.
#' @param filevars   List of strings, including the names and paths of
#'                   shapefiles to read in and save to, without extensions.
#' @param savekml    Boolean denoting whether or not to save a KML file.
#' @param quitopt    Text string for the cancel button.
#' @param bgcol      Text string containing UI background color.
#' @param buttoncol  Text string containing UI button color.
#' @param step       Integer step in the GAT program, for help reference.
#'
#' @examples
#'
#' if (interactive()) {
#' maskvars <- list(min = 100, max = 1000, unit = "meters",
#'                  point_id = "POINTID", bound_id = "GEOID10")
#' filevars <- list(
#'   pointin = paste(getwd(), "points", sep = "/"),
#'   boundin = paste(getwd(), "tracts", sep = "/"),
#'   userout = paste(getwd(), "geomasked", sep = "/")
#' )
#' confirmGMsettings(maskvars = maskvars, filevars = filevars)
#'
#' }
#'
#' @export

confirmGMsettings <- function(maskvars, filevars, savekml = FALSE, step = 0,
                              bgcol = "lightskyblue3", quitopt = "Quit",
                              buttoncol = "cornflowerblue") {
  coltest <- !"try-error" %in%
    class(try(grDevices::col2rgb(bgcol), silent = TRUE))
  if (!coltest) bgcol = "thistle1"
  coltest <- !"try-error" %in%
    class(try(grDevices::col2rgb(buttoncol), silent = TRUE))
  if (!coltest) buttoncol = "plum2"


  ## initial settings ####
  instruct <- paste("To modify a step, choose it from the list and click",
                    "'Confirm'. \n After you modify most steps, you will",
                    "return to this dialog. \n To continue, choose 'None',",
                    "then click 'Confirm'. \n",
                    "If you modify Step 1, the Geomasker will start over.")
  stepslist <- c("1. Point file and identifying variable",
                 "2. Boundary file and identifying variable",
                 "3. Minimum and maximum distances",
                 "4. Save KML file",
                 "5. Save location",
                 "None")
  fonthead <- tcltk::tkfont.create(family = "Segoe UI", size = 10, weight = "bold")



  # set up window ----
  tt <- tcltk::tktoplevel(background = bgcol)
  tcltk::tktitle(tt) <- paste0("Step ", step, ": Review settings")

  # define settings ----
  kml <- if (savekml) "Yes" else "No"
  min <- format(as.numeric(gsub(",", "", maskvars$min)),
                big.mark=",", scientific=FALSE)
  max <- format(as.numeric(gsub(",", "", maskvars$max)),
                big.mark=",", scientific=FALSE)

  mysets <- paste0("  ", stepslist[1],
                   "\n      ", filevars$pointin, " ",
                   "\n      ID variable: ", maskvars$point_id,
                   "\n  ", stepslist[2],
                   "\n      ", filevars$boundin,
                   "\n      ID variable: ", maskvars$bound_id,
                   "\n  ", stepslist[3],
                   "\n      Minimum distance: ", min,
                   "\n      Maximum distance: ", max,
                   "\n  ", stepslist[4], ": ", kml,
                   "\n  ", stepslist[5],
                   "\n      ", filevars$userout)


  # print settings ----
  tt$settl <- tcltk::tklabel(tt, text = "Settings", font = fonthead,
                              background = bgcol)
  tcltk::tkgrid(tt$settl, sticky = "w", padx = 5, pady = 5)
  tt$ins <- tcltk::tklabel(tt, text = mysets, justify = "left",
                           background = bgcol)
  tcltk::tkgrid(tt$ins, sticky = "w", padx = 5, pady = 5)
  tt$insttl <- tcltk::tklabel(tt, text = "Instructions", font = fonthead,
                              background = bgcol)
  tcltk::tkgrid(tt$insttl, sticky = "w", padx = 5, pady = 5)
  tt$ins <- tcltk::tklabel(tt, text = instruct, justify = "left",
                           background = bgcol)
  tcltk::tkgrid(tt$ins, sticky = "w", padx = 5, pady = 5)

  # request step selection ----
  tt$stepdir <- tcltk::tkframe(tt, background = bgcol)
  stepvar <- tcltk::tclVar("None")
  tt$stepdir$stepq <- tcltk::tklabel(tt$stepdir,
                      text = "Select the setting you wish to modify:",
                      background = bgcol)
  tt$stepdir$steplist <- tcltk::ttkcombobox(tt$stepdir, values = stepslist,
                         textvariable = stepvar, state = "readonly")
  tcltk::tkgrid(tt$stepdir$stepq, tt$stepdir$steplist, sticky = "w",
                padx = 5, pady = 5)
  tcltk::tkgrid(tt$stepdir)

  # help settings ----
  helppage <- "confirmGMsettings"
  hlp <- paste0("To continue, select a step to modify, \n",
                "or 'None' if you are finished, then click 'Confirm'. \n",
                "To start over, select Step 1.")

  myenv <- new.env()
  # button functions and layout
  onHelp <- function() {
    gatpkg::showGAThelp(help = hlp, helptitle = helppage, helppage = helppage,
                        step = step)
  }
  onOk <- function() {
    Rbval <- tcltk::tclvalue(stepvar)
    tcltk::tkdestroy(tt)
    assign("myvalue", Rbval, envir=myenv)
  }
  onCancel <- function() {
    tcltk::tkdestroy(tt)
    assign("myvalue", "cancel", envir=myenv)
  }

  # draw buttons ----
  tt$tf <- tcltk::tkframe(tt, background = bgcol)
  tt$tf$HelpBut <- tcltk::tkbutton(tt$tf, text="Help", width = 12,
                   command = onHelp, background = buttoncol)
  tt$tf$OkBut <- tcltk::tkbutton(tt$tf, text = "Confirm", width = 12,
                 command = onOk, default = "active", background = buttoncol)
  tt$tf$CancelBut <- tcltk::tkbutton(tt$tf, text = "Quit",
                     width = 12, command = onCancel, background = buttoncol)

  tcltk::tkgrid(tt$tf$OkBut, column = 2, row = 1, padx = 5)
  tcltk::tkgrid(tt$tf$CancelBut, column = 3, row = 1, padx = 5)
  tcltk::tkgrid(tt$tf$HelpBut, column = 4, row = 1, padx = 5)
  tcltk::tkgrid(tt$tf, padx = 1, pady = 5)

  # wait to continue ----
  tcltk::tkwait.window(tt)
  return(myenv$myvalue)
}
